name: Label PR for Review
on:
  pull_request:
    types: [opened, reopened]
jobs:
  add-label-and-project:
    runs-on: ubuntu-latest
    steps:
      - name: Adicionar label "needs-review"
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github-token: ${{ secrets.MY_PAT }}
          labels: needs-review

      - name: Adicionar PR ao Project Board
        uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/users/Fernando-Da-Costa/projects/1
          github-token: ${{ secrets.MY_PAT }}
